<?php
/*************************dashboard_servers.inc.php***********************************

	Created By	        :	Ruchi Chawla
	Last Modified By	:	Rahul Batra, 2008-06-01 
	Description	        :	This file is used for server connections
	Includes/Libraries	:	None
							
*******************************************************************************/ 



//////////TEST SERVER DECLARATIONS
GLOBAL $SERVER_CVCRMMASTER_TEST;
GLOBAL $SERVER_CVCRMMASTER_DB_TEST;
GLOBAL $SERVER_CVCRMMASTER_UN_TEST;
GLOBAL $SERVER_CVCRMMASTER_PW_TEST;

GLOBAL $SERVER_RESUMESLAVE_TEST;
GLOBAL $SERVER_RESUMESLAVE_DB_TEST;
GLOBAL $SERVER_RESUMESLAVE_UN_TEST;
GLOBAL $SERVER_RESUMESLAVE_PW_TEST;

GLOBAL $SERVER_RESUMEMASTER_TEST;
GLOBAL $SERVER_RESUMEMASTER_DB_TEST;
GLOBAL $SERVER_RESUMEMASTER_UN_TEST;
GLOBAL $SERVER_RESUMEMASTER_PW_TEST;

GLOBAL $SERVER_JOBSSLAVE_TEST;
GLOBAL $SERVER_JOBSSLAVE_DB_TEST;
GLOBAL $SERVER_JOBSSLAVE_UN_TEST;
GLOBAL $SERVER_JOBESLAVE_PW_TEST;

GLOBAL $SERVER_JOBSMASTER_TEST;
GLOBAL $SERVER_JOBSMASTER_DB_TEST;
GLOBAL $SERVER_JOBSMASTER_UN_TEST;
GLOBAL $SERVER_JOBSMASTER_PW_TEST;

GLOBAL $SERVER_NAUKRI_TEST;
GLOBAL $SERVER_NAUKRI_DB_TEST;
GLOBAL $SERVER_NAUKRI_UN_TEST;
GLOBAL $SERVER_NAUKRI_PW_TEST;

GLOBAL $SERVER_APPLYSLAVE_TEST;
GLOBAL $SERVER_APPLYSLAVE_DB_TEST;
GLOBAL $SERVER_APPLYSLAVE_UN_TEST;
GLOBAL $SERVER_APPLYSLAVE_PW_TEST;

GLOBAL $SERVER_APPLYMASTER_TEST;
GLOBAL $SERVER_APPLYMASTER_DB_TEST;
GLOBAL $SERVER_APPLYMASTER_UN_TEST;
GLOBAL $SERVER_APPLYMASTER_PW_TEST;

/////////////////LIVE SERVER DECLARATIONS
GLOBAL $SERVER_CVCRMMASTER_LIVE;
GLOBAL $SERVER_CVCRMMASTER_DB_LIVE;
GLOBAL $SERVER_CVCRMMASTER_UN_LIVE;
GLOBAL $SERVER_CVCRMMASTER_PW_LIVE;

GLOBAL $SERVER_RESUMESLAVE_LIVE;
GLOBAL $SERVER_RESUMESLAVE_DB_LIVE;
GLOBAL $SERVER_RESUMESLAVE_UN_LIVE;
GLOBAL $SERVER_RESUMESLAVE_PW_LIVE;

GLOBAL $SERVER_ACTUALRESUMESLAVE_LIVE;
GLOBAL $SERVER_ACTUALRESUMESLAVE_DB_LIVE;
GLOBAL $SERVER_ACTUALRESUMESLAVE_UN_LIVE;
GLOBAL $SERVER_ACTUALRESUMESLAVE_PW_LIVE;

GLOBAL $SERVER_RESUMEMASTER_LIVE;
GLOBAL $SERVER_RESUMEMASTER_DB_LIVE;
GLOBAL $SERVER_RESUMEMASTER_UN_LIVE;
GLOBAL $SERVER_RESUMEMASTER_PW_LIVE;

GLOBAL $SERVER_JOBSSLAVE_LIVE;
GLOBAL $SERVER_JOBSSLAVE_DB_LIVE;
GLOBAL $SERVER_JOBSSLAVE_UN_LIVE;
GLOBAL $SERVER_JOBESLAVE_PW_LIVE;

GLOBAL $SERVER_JOBSMASTER_LIVE;
GLOBAL $SERVER_JOBSMASTER_DB_LIVE;
GLOBAL $SERVER_JOBSMASTER_UN_LIVE;
GLOBAL $SERVER_JOBSMASTER_PW_LIVE;

GLOBAL $SERVER_NAUKRI_LIVE;
GLOBAL $SERVER_NAUKRI_DB_LIVE;
GLOBAL $SERVER_NAUKRI_UN_LIVE;
GLOBAL $SERVER_NAUKRI_PW_LIVE;

GLOBAL $SERVER_NAUKRITMS_LIVE;
GLOBAL $SERVER_NAUKRITMS_DB_LIVE;
GLOBAL $SERVER_NAUKRITMS_UN_LIVE;
GLOBAL $SERVER_NAUKRITMS_PW_LIVE;

GLOBAL $SERVER_APPLYSLAVE_LIVE;
GLOBAL $SERVER_APPLYSLAVE_DB_LIVE;
GLOBAL $SERVER_APPLYSLAVE_UN_LIVE;
GLOBAL $SERVER_APPLYSLAVE_PW_LIVE;

GLOBAL $SERVER_APPLYMASTER_LIVE;
GLOBAL $SERVER_APPLYMASTER_DB_LIVE;
GLOBAL $SERVER_APPLYMASTER_UN_LIVE;
GLOBAL $SERVER_APPLYMASTER_PW_LIVE;


//////////DECLARATIONS FOR SERVERS BEING USED
GLOBAL $SERVER_CVCRMMASTER;
GLOBAL $SERVER_CVCRMMASTER_DB;
GLOBAL $SERVER_CVCRMMASTER_UN;
GLOBAL $SERVER_CVCRMMASTER_PW;

GLOBAL $SERVER_RESUMESLAVE;
GLOBAL $SERVER_RESUMESLAVE_DB;
GLOBAL $SERVER_RESUMESLAVE_UN;
GLOBAL $SERVER_RESUMESLAVE_PW;

GLOBAL $SERVER_ACTUALRESUMESLAVE;
GLOBAL $SERVER_ACTUALRESUMESLAVE_DB;
GLOBAL $SERVER_ACTUALRESUMESLAVE_UN;
GLOBAL $SERVER_ACTUALRESUMESLAVE_PW;

GLOBAL $SERVER_RESUMEMASTER;
GLOBAL $SERVER_RESUMEMASTER_DB;
GLOBAL $SERVER_RESUMEMASTER_UN;
GLOBAL $SERVER_RESUMEMASTER_PW;

GLOBAL $SERVER_JOBSSLAVE;
GLOBAL $SERVER_JOBSSLAVE_DB;
GLOBAL $SERVER_JOBSSLAVE_UN;
GLOBAL $SERVER_JOBESLAVE_PW;

GLOBAL $SERVER_JOBSMASTER;
GLOBAL $SERVER_JOBSMASTER_DB;
GLOBAL $SERVER_JOBSMASTER_UN;
GLOBAL $SERVER_JOBSMASTER_PW;

GLOBAL $SERVER_NAUKRI;
GLOBAL $SERVER_NAUKRI_DB;
GLOBAL $SERVER_NAUKRI_UN;
GLOBAL $SERVER_NAUKRI_PW;

GLOBAL $SERVER_NAUKRITMS;
GLOBAL $SERVER_NAUKRITMS_DB;
GLOBAL $SERVER_NAUKRITMS_UN;
GLOBAL $SERVER_NAUKRITMS_PW;

GLOBAL $SERVER_APPLYSLAVE;
GLOBAL $SERVER_APPLYSLAVE_DB;
GLOBAL $SERVER_APPLYSLAVE_UN;
GLOBAL $SERVER_APPLYSLAVE_PW;

GLOBAL $SERVER_APPLYMASTER;
GLOBAL $SERVER_APPLYMASTER_DB;
GLOBAL $SERVER_APPLYMASTER_UN;
GLOBAL $SERVER_APPLYMASTER_PW;
//*! icops
GLOBAL $SERVER_NEWRESUMESLAVE;
GLOBAL $SERVER_NEWRESUMESLAVE_DB;
GLOBAL $SERVER_NEWRESUMESLAVE_UN;
GLOBAL $SERVER_NEWRESUMESLAVE_PW;
//*! icops

/******TEST SERVERS******/
$SERVER_CVCRMMASTER_TEST="192.168.2.251";
$SERVER_CVCRMMASTER_DB_TEST="manager";
$SERVER_CVCRMMASTER_UN_TEST="root";
$SERVER_CVCRMMASTER_PW_TEST="Km7Iv80l";

$SERVER_RESUMESLAVE_TEST="192.168.2.251";
$SERVER_RESUMESLAVE_DB_TEST="manager";
$SERVER_RESUMESLAVE_UN_TEST="root";
$SERVER_RESUMESLAVE_PW_TEST="Km7Iv80l";

$SERVER_RESUMEMASTER_TEST="192.168.2.251";
$SERVER_RESUMEMASTER_DB_TEST="manager";
$SERVER_RESUMEMASTER_UN_TEST="root";
$SERVER_RESUMEMASTER_PW_TEST="Km7Iv80l";

$SERVER_JOBSSLAVE_TEST="192.168.2.251";
$SERVER_JOBSSLAVE_DB_TEST="manager";
$SERVER_JOBSSLAVE_UN_TEST="root";
$SERVER_JOBESLAVE_PW_TEST="Km7Iv80l";

$SERVER_JOBSMASTER_TEST="192.168.2.251";
$SERVER_JOBSMASTER_DB_TEST="manager";
$SERVER_JOBSMASTER_UN_TEST="root";
$SERVER_JOBSMASTER_PW_TEST="Km7Iv80l";

$SERVER_NAUKRI_TEST="192.168.2.251";
$SERVER_NAUKRI_DB_TEST="manager";
$SERVER_NAUKRI_UN_TEST="root";
$SERVER_NAUKRI_PW_TEST="Km7Iv80l";

$SERVER_APPLYSLAVE_TEST="172.16.3.212:3317";
$SERVER_APPLYSLAVE_DB_TEST="mynaukri";
$SERVER_APPLYSLAVE_UN_TEST="root";
$SERVER_APPLYSLAVE_PW_TEST="Km7Iv80l";

$SERVER_APPLYMASTER_TEST="172.16.3.212:3317";
$SERVER_APPLYMASTER_DB_TEST="mynaukri";
$SERVER_APPLYMASTER_UN_TEST="root";
$SERVER_APPLYMASTER_PW_TEST="Km7Iv80l";


/******LIVE SERVERS******/
//$SERVER_CVCRMMASTER_LIVE="10.208.67.208:3306";
$SERVER_CVCRMMASTER_LIVE="db2.resdex.com";
$SERVER_CVCRMMASTER_DB_LIVE="db1";
$SERVER_CVCRMMASTER_UN_LIVE="mynauk";
$SERVER_CVCRMMASTER_PW_LIVE="mynaukKm7Iv80l";

$SERVER_RESUMESLAVE_LIVE="dashboard1.resdex.com:3306";
$SERVER_RESUMESLAVE_DB_LIVE="db1";
$SERVER_RESUMESLAVE_UN_LIVE="dashboard";
$SERVER_RESUMESLAVE_PW_LIVE="dashboardKm7Iv80l";

/*
$SERVER_RESUMESLAVE_LIVE="dashboard1.slave.resdex.com:3316";
$SERVER_RESUMESLAVE_DB_LIVE="resman5";
$SERVER_RESUMESLAVE_UN_LIVE="dashboard";
$SERVER_RESUMESLAVE_PW_LIVE="dashboardKm7Iv80l";
*/

//$SERVER_RESUMEMASTER_LIVE="198.65.131.141";
$SERVER_RESUMEMASTER_LIVE="resman1.resdex.com";
$SERVER_RESUMEMASTER_DB_LIVE="db1";
$SERVER_RESUMEMASTER_UN_LIVE="dashboard";
$SERVER_RESUMEMASTER_PW_LIVE="dashboardKm7Iv80l";

//$SERVER_JOBSSLAVE_LIVE="198.64.158.65";
$SERVER_JOBSSLAVE_LIVE="10.208.65.123";
$SERVER_JOBSSLAVE_DB_LIVE="hotjobs1";
$SERVER_JOBSSLAVE_UN_LIVE="jobs";
$SERVER_JOBSSLAVE_PW_LIVE="Km7Iv80l";

//$SERVER_JOBSMASTER_LIVE="130.94.22.225";
$SERVER_JOBSMASTER_LIVE="10.208.65.163";
$SERVER_JOBSMASTER_DB_LIVE="hotjobs1";
$SERVER_JOBSMASTER_UN_LIVE="jobs";
$SERVER_JOBSMASTER_PW_LIVE="Km7Iv80l";

//$SERVER_NAUKRI_LIVE="198.64.153.138";
$SERVER_NAUKRI_LIVE="10.208.65.160";
$SERVER_NAUKRI_DB_LIVE="mailers";
$SERVER_NAUKRI_UN_LIVE="mailer";
$SERVER_NAUKRI_PW_LIVE="Km7Iv80l";

$SERVER_APPLYSLAVE_LIVE="dashboard.applyslave.resdex.com:3307";
$SERVER_APPLYSLAVE_DB_LIVE="mynaukri";
$SERVER_APPLYSLAVE_UN_LIVE="dashboard";
$SERVER_APPLYSLAVE_PW_LIVE="dashboardKm7Iv80l";

$SERVER_APPLYMASTER_LIVE="apply2.resdex.com";
$SERVER_APPLYMASTER_DB_LIVE="mynaukri";
$SERVER_APPLYMASTER_UN_LIVE="dashacm";
$SERVER_APPLYMASTER_PW_LIVE="dashacmKm7Iv80l";

//$SERVER_NAUKRITMS_LIVE="198.64.153.138";
// Old TMS database
//$SERVER_NAUKRITMS_LIVE="10.208.65.121:3307";

// New TMS database
$SERVER_NAUKRITMS_LIVE="tms.resdex.com";
//$SERVER_NAUKRITMS_LIVE="tms.resdex.com";
$SERVER_NAUKRITMS_DB_LIVE="TMS";
$SERVER_NAUKRITMS_UN_LIVE="dashboard";
$SERVER_NAUKRITMS_PW_LIVE="dashboardKm7Iv80l";

//*! icops
//$SERVER_NEWRESUMESLAVE_LIVE="10.208.65.224";
//$SERVER_NEWRESUMESLAVE_LIVE="icops1.resdex.com";
$SERVER_NEWRESUMESLAVE_LIVE="dashboard1.resdex.com:3306";
$SERVER_NEWRESUMESLAVE_DB_LIVE="db1";
$SERVER_NEWRESUMESLAVE_UN_LIVE="dashboard";
$SERVER_NEWRESUMESLAVE_PW_LIVE="dashboardKm7Iv80l";
//*! icops

//*! 276
//$SERVER_276RESUMESLAVE_LIVE="10.208.68.200";
//$SERVER_276RESUMESLAVE_LIVE="dashboard1.slave.resdex.com";
$SERVER_276RESUMESLAVE_LIVE="dashboard2.slave.resdex.com:3308";
$SERVER_276RESUMESLAVE_DB_LIVE="resman5";
$SERVER_276RESUMESLAVE_UN_LIVE="dashboard";
$SERVER_276RESUMESLAVE_PW_LIVE="dashboardKm7Iv80l";
//*! 276



/******SERVERS BEING USED******/
$SERVER_CVCRMMASTER=$SERVER_CVCRMMASTER_LIVE;
$SERVER_CVCRMMASTER_DB=$SERVER_CVCRMMASTER_DB_LIVE;
$SERVER_CVCRMMASTER_UN=$SERVER_CVCRMMASTER_UN_LIVE;
$SERVER_CVCRMMASTER_PW=$SERVER_CVCRMMASTER_PW_LIVE;

$SERVER_RESUMESLAVE=$SERVER_RESUMESLAVE_LIVE;
$SERVER_RESUMESLAVE_DB=$SERVER_RESUMESLAVE_DB_LIVE;
$SERVER_RESUMESLAVE_UN=$SERVER_RESUMESLAVE_UN_LIVE;
$SERVER_RESUMESLAVE_PW=$SERVER_RESUMESLAVE_PW_LIVE;

$SERVER_ACTUALRESUMESLAVE=$SERVER_DASHBOARD_LIVE;
$SERVER_ACTUALRESUMESLAVE_DB=$SERVER_DASHBOARD_DB_LIVE;
$SERVER_ACTUALRESUMESLAVE_UN=$SERVER_DASHBOARD_UN_LIVE;
$SERVER_ACTUALRESUMESLAVE_PW=$SERVER_DASHBOARD_PW_LIVE;

$SERVER_RESUMEMASTER=$SERVER_RESUMEMASTER_LIVE;
$SERVER_RESUMEMASTER_DB=$SERVER_RESUMEMASTER_DB_LIVE;
$SERVER_RESUMEMASTER_UN=$SERVER_RESUMEMASTER_UN_LIVE;
$SERVER_RESUMEMASTER_PW=$SERVER_RESUMEMASTER_PW_LIVE;

$SERVER_JOBSSLAVE=$SERVER_JOBSSLAVE_LIVE;
$SERVER_JOBSSLAVE_DB=$SERVER_JOBSSLAVE_DB_LIVE;
$SERVER_JOBSSLAVE_UN=$SERVER_JOBSSLAVE_UN_LIVE;
$SERVER_JOBESLAVE_PW=$SERVER_JOBESLAVE_PW_LIVE;

$SERVER_JOBSMASTER=$SERVER_JOBSMASTER_LIVE;
$SERVER_JOBSMASTER_DB=$SERVER_JOBSMASTER_DB_LIVE;
$SERVER_JOBSMASTER_UN=$SERVER_JOBSMASTER_UN_LIVE;
$SERVER_JOBSMASTER_PW=$SERVER_JOBSMASTER_PW_LIVE;

$SERVER_NAUKRI=$SERVER_NAUKRI_LIVE;
$SERVER_NAUKRI_DB=$SERVER_NAUKRI_DB_LIVE;
$SERVER_NAUKRI_UN=$SERVER_NAUKRI_UN_LIVE;
$SERVER_NAUKRI_PW=$SERVER_NAUKRI_PW_LIVE;

$SERVER_NAUKRITMS = $SERVER_NAUKRITMS_LIVE;
$SERVER_NAUKRITMS_DB = $SERVER_NAUKRITMS_DB_LIVE;
$SERVER_NAUKRITMS_UN = $SERVER_NAUKRITMS_UN_LIVE;
$SERVER_NAUKRITMS_PW = $SERVER_NAUKRITMS_PW_LIVE;

$SERVER_APPLYSLAVE=$SERVER_APPLYSLAVE_LIVE;
$SERVER_APPLYSLAVE_DB=$SERVER_APPLYSLAVE_DB_LIVE;
$SERVER_APPLYSLAVE_UN=$SERVER_APPLYSLAVE_UN_LIVE;
$SERVER_APPLYSLAVE_PW=$SERVER_APPLYSLAVE_PW_LIVE;

$SERVER_APPLYMASTER=$SERVER_APPLYMASTER_LIVE;
$SERVER_APPLYMASTER_DB=$SERVER_APPLYMASTER_DB_LIVE;
$SERVER_APPLYMASTER_UN=$SERVER_APPLYMASTER_UN_LIVE;
$SERVER_APPLYMASTER_PW=$SERVER_APPLYMASTER_PW_LIVE;
//*! icops
$SERVER_NEWRESUMESLAVE=$SERVER_NEWRESUMESLAVE_LIVE;
$SERVER_NEWRESUMESLAVE_DB=$SERVER_NEWRESUMESLAVE_DB_LIVE;
$SERVER_NEWRESUMESLAVE_UN=$SERVER_NEWRESUMESLAVE_UN_LIVE;
$SERVER_NEWRESUMESLAVE_PW=$SERVER_NEWRESUMESLAVE_PW_LIVE;
//*! icops


//*! 276
$SERVER_276RESUMESLAVE=$SERVER_276RESUMESLAVE_LIVE;
$SERVER_276RESUMESLAVE_DB=$SERVER_276RESUMESLAVE_DB_LIVE;
$SERVER_276RESUMESLAVE_UN=$SERVER_276RESUMESLAVE_UN_LIVE;
$SERVER_276RESUMESLAVE_PW=$SERVER_276RESUMESLAVE_PW_LIVE;
//*! 276


GLOBAL $SERVERS_ARR;

$SERVERS_ARR=array();
$SERVERS_ARR[strtoupper($SERVER_CVCRMMASTER)]=array("SERVER"=>$SERVER_CVCRMMASTER , "USERNAME"=>$SERVER_CVCRMMASTER_UN , "PASSWORD"=>$SERVER_CVCRMMASTER_PW,"DATABASE"=>$SERVER_CVCRMMASTER_DB);

$SERVERS_ARR[strtoupper($SERVER_RESUMESLAVE)]=array("SERVER"=>$SERVER_RESUMESLAVE , "USERNAME"=>$SERVER_RESUMESLAVE_UN , "PASSWORD"=>$SERVER_RESUMESLAVE_PW,"DATABASE"=>$SERVER_RESUMESLAVE_DB);

$SERVERS_ARR[strtoupper($SERVER_ACTUALRESUMESLAVE)]=array("SERVER"=>$SERVER_DASHBOARD , "USERNAME"=>$SERVER_DASHBOARD_UN , "PASSWORD"=>$SERVER_DASHBOARD_PW,"DATABASE"=>$SERVER_DASHBOARD_DB);

$SERVERS_ARR[strtoupper($SERVER_RESUMEMASTER)]=array("SERVER"=>$SERVER_RESUMEMASTER , "USERNAME"=>$SERVER_RESUMEMASTER_UN , "PASSWORD"=>$SERVER_RESUMEMASTER_PW,"DATABASE"=>$SERVER_RESUMEMASTER_DB);

$SERVERS_ARR[strtoupper($SERVER_JOBSSLAVE)]=array("SERVER"=>$SERVER_JOBSSLAVE , "USERNAME"=>$SERVER_JOBSSLAVE_UN , "PASSWORD"=>$SERVER_JOBSSLAVE_PW,"DATABASE"=>$SERVER_JOBSSLAVE_DB);

$SERVERS_ARR[strtoupper($SERVER_JOBSMASTER)]=array("SERVER"=>$SERVER_JOBSMASTER , "USERNAME"=>$SERVER_JOBSMASTER_UN , "PASSWORD"=>$SERVER_JOBSMASTER_PW,"DATABASE"=>$SERVER_JOBSMASTER_DB);

$SERVERS_ARR[strtoupper($SERVER_NAUKRI)]=array("SERVER"=>$SERVER_NAUKRI , "USERNAME"=>$SERVER_NAUKRI_UN , "PASSWORD"=>$SERVER_NAUKRI_PW,"DATABASE"=>$SERVER_NAUKRI_DB);

$SERVERS_ARR[strtoupper($SERVER_NAUKRITMS)]=array("SERVER"=>$SERVER_NAUKRITMS , "USERNAME"=>$SERVER_NAUKRITMS_UN , "PASSWORD"=>$SERVER_NAUKRITMS_PW,"DATABASE"=>$SERVER_NAUKRITMS_DB);

$SERVERS_ARR[strtoupper($SERVER_APPLYSLAVE)]=array("SERVER"=>$SERVER_APPLYSLAVE , "USERNAME"=>$SERVER_APPLYSLAVE_UN , "PASSWORD"=>$SERVER_APPLYSLAVE_PW,"DATABASE"=>$SERVER_APPLYSLAVE_DB);

$SERVERS_ARR[strtoupper($SERVER_APPLYMASTER)]=array("SERVER"=>$SERVER_APPLYMASTER , "USERNAME"=>$SERVER_APPLYMASTER_UN , "PASSWORD"=>$SERVER_APPLYMASTER_PW,"DATABASE"=>$SERVER_APPLYMASTER_DB);

//*! icops
$SERVERS_ARR[strtoupper($SERVER_NEWRESUMESLAVE)]=array("SERVER"=>$SERVER_NEWRESUMESLAVE , "USERNAME"=>$SERVER_NEWRESUMESLAVE_UN , "PASSWORD"=>$SERVER_NEWRESUMESLAVE_PW,"DATABASE"=>$SERVER_NEWRESUMESLAVE_DB);

//*! 276
$SERVERS_ARR[strtoupper($SERVER_276RESUMESLAVE)]=array("SERVER"=>$SERVER_276RESUMESLAVE , "USERNAME"=>$SERVER_276RESUMESLAVE_UN , "PASSWORD"=>$SERVER_276RESUMESLAVE_PW,"DATABASE"=>$SERVER_276RESUMESLAVE_DB);
